-- This file was generated by galactic dumper | V2.3
local loaded = loadstring([=[
-- Create ScreenGui
local screenGui = Instance.new("ScreenGui")
screenGui.Name = "FEFighterGUI"
screenGui.Parent = game.CoreGui
-- Create the Frame
local frame = Instance.new("Frame")
frame.Size = UDim2.new(0, 200, 0, 120)
frame.Position = UDim2.new(0.5, -100, 0.5, -60)
frame.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
frame.BorderSizePixel = 2
frame.Active = true
frame.Draggable = true
frame.Parent = screenGui
-- Title Label
local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, 0, 0, 25)
title.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
title.BorderSizePixel = 2
title.Text = "FE Fighter"
title.TextColor3 = Color3.fromRGB(255, 255, 255)
title.Font = Enum.Font.GothamBold
title.TextScaled = true
title.Parent = frame
-- Execute Button
local TextButton = Instance.new("TextButton")
TextButton.Size = UDim2.new(0.8, 0, 0.25, 0)
TextButton.Position = UDim2.new(0.1, 0, 0.35, 0)
TextButton.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
TextButton.BorderSizePixel = 2
TextButton.Text = "Run FE Fighter"
TextButton.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton.Font = Enum.Font.GothamBold
TextButton.TextScaled = true
TextButton.Parent = frame
-- Stop Button
local TextButton2 = Instance.new("TextButton")
TextButton2.Size = UDim2.new(0.8, 0, 0.25, 0)
TextButton2.Position = UDim2.new(0.1, 0, 0.65, 0)
TextButton2.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
TextButton2.BorderSizePixel = 2
TextButton2.Text = "Stop Anim"
TextButton2.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton2.Font = Enum.Font.GothamBold
TextButton2.TextScaled = true
TextButton2.Parent = frame
-- State Variable
local isRunning = false -- Tracks whether the FE Fighter script is running
-- FE Fighter Script
local var = [[
    -- Replace with your FE Fighter script
    loadstring(game:HttpGet("https://pastefy.app/E6ST33gy/raw"))()
]]
-- Execute FE Fighter
TextButton.MouseButton1Click:Connect(function()
    if not isRunning then
        isRunning = true
        TextButton.Text = "Running..."
        TextButton.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
        TextButton.Active = false -- Disable button
        
        -- Try executing the script
        local success, err = pcall(function()
            loadstring(var)()
        end)
        if not success then
            warn("Error executing FE Fighter script: " .. err)
            isRunning = false
            TextButton.Text = "Run FE Fighter"
            TextButton.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
            TextButton.Active = true
        end
    end
end)
-- Stop Animations
TextButton2.MouseButton1Click:Connect(function()
    -- Remove tools
    for _, toolName in ipairs({"Punch", "Defense"}) do
        local tool = game.Players.LocalPlayer.Backpack:FindFirstChild(toolName)
        if tool then
            tool:Destroy()
        end
        local findFirstChild = game.Players.LocalPlayer.Character:FindFirstChild(toolName)
        if findFirstChild then
            findFirstChild:Destroy()
        end
    end
    -- Stop animations
    local character = game.Players.LocalPlayer.Character
    if character then
        local humanoid = character:FindFirstChild("Humanoid")
        if humanoid then
            local animator = humanoid:FindFirstChild("Animator")
            if animator then
                for _, track in ipairs(animator:GetPlayingAnimationTracks()) do
                    track.Looped = false
                    track:Stop(0)
                end
            end
        end
        -- Disconnect animation connections
        local connections = getconnections(game:GetService("RunService").Stepped)
        for _, connection in ipairs(connections) do
            connection:Disable()
        end
        -- Remove effects
        for _, obj in ipairs(character:GetDescendants()) do
            if obj:IsA("Highlight") or obj:IsA("Part") or obj:IsA("Sound") then
                obj:Destroy()
            end
        end
    end
    -- Re-enable Execute Button
    isRunning = false
    TextButton.Text = "Run FE Fighter"
    TextButton.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
    TextButton.Active = true
end)
-- Notification
game.StarterGui:SetCore("SendNotification", {
    Title = "YT: G10",
    Text = "Stop Anim makes you reset!",
    Duration = 7,
    Button1 = "Alright"
})
]=])()
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "FEFighterGUI"
ScreenGui.Parent = game:GetService("CoreGui")
local Frame = Instance.new("Frame")
Frame.Size = UDim2.new(0, 200, 0, 120)
Frame.Position = UDim2.new(0.5, -100, 0.5, -60)
Frame.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
Frame.BorderSizePixel = 2
Frame.Active = true
Frame.Draggable = true
Frame.Parent = ScreenGui
local TextLabel = Instance.new("TextLabel")
TextLabel.Size = UDim2.new(1, 0, 0, 25)
TextLabel.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
TextLabel.BorderSizePixel = 2
TextLabel.Text = "FE Fighter"
TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel.Font = Enum.Font.GothamBold
TextLabel.TextScaled = true
TextLabel.Parent = Frame
local TextButton3 = Instance.new("TextButton")
TextButton3.Size = UDim2.new(0.8, 0, 0.25, 0)
TextButton3.Position = UDim2.new(0.1, 0, 0.35, 0)
TextButton3.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
TextButton3.BorderSizePixel = 2
TextButton3.Text = "Run FE Fighter"
TextButton3.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton3.Font = Enum.Font.GothamBold
TextButton3.TextScaled = true
TextButton3.Parent = Frame
local TextButton4 = Instance.new("TextButton")
TextButton4.Size = UDim2.new(0.8, 0, 0.25, 0)
TextButton4.Position = UDim2.new(0.1, 0, 0.65, 0)
TextButton4.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
TextButton4.BorderSizePixel = 2
TextButton4.Text = "Stop Anim"
TextButton4.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton4.Font = Enum.Font.GothamBold
TextButton4.TextScaled = true
TextButton4.Parent = Frame
TextButton3:Connect(function(arg1, arg2, arg3)
    TextButton3.Text = "Running..."
    TextButton3.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
    TextButton3.Active = false
    local loaded2 = loadstring([=[
    -- Replace with your FE Fighter script
    loadstring(game:HttpGet("https://pastefy.app/E6ST33gy/raw"))()
]=])()
    local loaded3 = loadstring(game:HttpGet("https://pastefy.app/E6ST33gy/raw", true))()
end)
TextButton4:Connect(function(arg1, arg2, arg3)
    for key_1, val_1 in ipairs({
                'Punch',
                'Defense'
            }) do
    local Players = game:GetService("Players").LocalPlayer.Backpack:FindFirstChild('Punch')
    local RunService = game:GetService("RunService")
    Players:Destroy()
    local Players2 = game:GetService("Players").LocalPlayer.Character:FindFirstChild('Punch')
    Players2:Destroy()
    local Players3 = game:GetService("Players").LocalPlayer.Backpack:FindFirstChild('Defense')
    Players3:Destroy()
    local Players4 = game:GetService("Players").LocalPlayer.Character:FindFirstChild('Defense')
    Players4:Destroy()
    end
    local Players5 = game:GetService("Players").LocalPlayer.Character:FindFirstChild('Humanoid')
    local Animator = Players5:FindFirstChild('Animator')
    local getPlayingAnimationTracks = Animator:GetPlayingAnimationTracks()
    val_14.Looped = false
    local stop = val_14:Stop(0)
    local getconnectionsResult = getconnections({
        Wait = function(arg1, arg2, arg3)
            game:GetService("RunService").Stepped:Wait()
            return nil
        end,
        Connect = function(arg1, arg2)
            local RunService = game:GetService("RunService").Stepped:Connect(arg2)
for i = 1, 249 do
                local arg2Result = arg2(0.0016)
end
        end
    })
    local disable = val_18:Disable()
    local Players6 = game:GetService("Players").LocalPlayer.Character:GetDescendants()
    local highlight = val_20:IsA('Highlight')
    val_20:Destroy()
    TextButton3.Text = "Run FE Fighter"
    TextButton3.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
    TextButton3.Active = true
end)
game:GetService("StarterGui"):SetCore('SendNotification', {
    Duration = 7,
    Text = 'Stop Anim makes you reset!',
    Title = 'YT: G10',
    Button1 = 'Alright'
})
